# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Lenovo\Desktop\KOU\TM MARM-99 2021\turksat-muy-ground-station-2021\exercises\cameraViewer\cameraViewer.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1304, 779)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.ViewerLabel = QtWidgets.QLabel(Form)
        self.ViewerLabel.setMinimumSize(QtCore.QSize(1280, 720))
        self.ViewerLabel.setText("")
        self.ViewerLabel.setObjectName("ViewerLabel")
        self.verticalLayout.addWidget(self.ViewerLabel)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.startLabel = QtWidgets.QPushButton(Form)
        self.startLabel.setMinimumSize(QtCore.QSize(0, 0))
        self.startLabel.setMaximumSize(QtCore.QSize(16777215, 40))
        self.startLabel.setObjectName("startLabel")
        self.verticalLayout_2.addWidget(self.startLabel)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.startLabel.setText(_translate("Form", "bas"))
