# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Lenovo\Desktop\KOU\TM MARM-99 2021\turksat-muy-ground-station-2021\templates\MainGUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainGUI(object):
    def setupUi(self, MainGUI):
        MainGUI.setObjectName("MainGUI")
        MainGUI.resize(1689, 877)
        icon = QtGui.QIcon.fromTheme("tm-marm99")
        MainGUI.setWindowIcon(icon)
        MainGUI.setStyleSheet("QMainWindow{\n"
"background-image: url(:/tm_marm99/space.jpg);\n"
"}\n"
"\n"
"\n"
"QStatusBar{\n"
"background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:1, y2:0, stop:0.288557 rgba(0, 0, 0, 224), stop:1 rgba(235, 235, 235, 0));\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainGUI)
        self.centralwidget.setStyleSheet("margin:0px;\n"
"padding:0px;\n"
"background:rgba(0,0,0,0.7);\n"
"border-width:3px;\n"
"")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.title_bar_layout = QtWidgets.QHBoxLayout()
        self.title_bar_layout.setSpacing(0)
        self.title_bar_layout.setObjectName("title_bar_layout")
        self.left_bar = QtWidgets.QFrame(self.centralwidget)
        self.left_bar.setEnabled(True)
        self.left_bar.setMinimumSize(QtCore.QSize(100, 38))
        self.left_bar.setMaximumSize(QtCore.QSize(16777215, 38))
        self.left_bar.setStyleSheet("QFrame{\n"
"background:rgba(0,0,0,0.38);\n"
"}\n"
"QFrame{\n"
"border-radius:none;\n"
"}\n"
"\n"
"QFrame:hover{\n"
"background:rgba(0,0,0,0.40);\n"
"}")
        self.left_bar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.left_bar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.left_bar.setObjectName("left_bar")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.left_bar)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.left_bar)
        self.label.setMaximumSize(QtCore.QSize(35, 16777215))
        self.label.setStyleSheet("QLabel{\n"
"background:#3b3937;\n"
"color:#fff;\n"
"border-radius:none;\n"
"padding-top:-2px;\n"
"padding-left:7px;\n"
"}\n"
"")
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.title_label = QtWidgets.QLabel(self.left_bar)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.title_label.setFont(font)
        self.title_label.setStyleSheet("QLabel{\n"
"background:#3b3937;\n"
"color:rgb(227, 227, 227);\n"
"border-radius:none;\n"
"padding-top:-1px;\n"
"padding-left:4px;\n"
"\n"
"font-size:15px;\n"
"}\n"
"")
        self.title_label.setObjectName("title_label")
        self.horizontalLayout.addWidget(self.title_label)
        self.title_bar_layout.addWidget(self.left_bar)
        self.right_bar = QtWidgets.QFrame(self.centralwidget)
        self.right_bar.setEnabled(True)
        self.right_bar.setMinimumSize(QtCore.QSize(180, 38))
        self.right_bar.setMaximumSize(QtCore.QSize(180, 38))
        self.right_bar.setStyleSheet("QFrame{\n"
"background:rgba(0,0,0,0.38);\n"
"}\n"
"QFrame{\n"
"border-radius:none;\n"
"}\n"
"\n"
"QFrame:hover{\n"
"background:rgba(0,0,0,0.40);\n"
"}")
        self.right_bar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.right_bar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.right_bar.setObjectName("right_bar")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.right_bar)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.button_minimize = QtWidgets.QPushButton(self.right_bar)
        self.button_minimize.setMinimumSize(QtCore.QSize(60, 38))
        self.button_minimize.setMaximumSize(QtCore.QSize(60, 38))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.button_minimize.setFont(font)
        self.button_minimize.setStyleSheet("QPushButton{\n"
"background:#3b3937;\n"
"color:#fff;\n"
"\n"
"border-radius:none;\n"
"\n"
"padding-top:-7px\n"
"}\n"
"\n"
"\n"
"QPushButton:hover{\n"
"background:rgb(79, 76, 74);\n"
"color:white\n"
"}")
        self.button_minimize.setObjectName("button_minimize")
        self.horizontalLayout_3.addWidget(self.button_minimize)
        self.button_max_min = QtWidgets.QPushButton(self.right_bar)
        self.button_max_min.setMinimumSize(QtCore.QSize(60, 38))
        self.button_max_min.setMaximumSize(QtCore.QSize(60, 38))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.button_max_min.setFont(font)
        self.button_max_min.setStyleSheet("QPushButton{\n"
"background:#3b3937;\n"
"color:#fff;\n"
"\n"
"border-radius:none;\n"
"padding-top:-3px\n"
"}\n"
"\n"
"\n"
"QPushButton:hover{\n"
"background:#4f4c4a;\n"
"color:white\n"
"}")
        self.button_max_min.setObjectName("button_max_min")
        self.horizontalLayout_3.addWidget(self.button_max_min)
        self.button_close = QtWidgets.QPushButton(self.right_bar)
        self.button_close.setMinimumSize(QtCore.QSize(60, 38))
        self.button_close.setMaximumSize(QtCore.QSize(60, 38))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.button_close.setFont(font)
        self.button_close.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.button_close.setStyleSheet("QPushButton{\n"
"background:#3b3937;\n"
"color:#fff;\n"
"\n"
"border-radius:none;\n"
"}\n"
"\n"
"\n"
"QPushButton:hover{\n"
"background:#e81123;\n"
"color:white\n"
"}")
        self.button_close.setObjectName("button_close")
        self.horizontalLayout_3.addWidget(self.button_close, 0, QtCore.Qt.AlignLeft)
        self.title_bar_layout.addWidget(self.right_bar)
        self.verticalLayout_2.addLayout(self.title_bar_layout)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setMinimumSize(QtCore.QSize(0, 0))
        self.frame.setStyleSheet("background:rgba(255, 255, 255,0.1);;\n"
"margin:10px;\n"
"border-width:0px;\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.topFrame = QtWidgets.QFrame(self.frame)
        self.topFrame.setMinimumSize(QtCore.QSize(0, 0))
        self.topFrame.setMaximumSize(QtCore.QSize(16777215, 280))
        self.topFrame.setStyleSheet("QPushButton{\n"
"background:rgb(79, 117, 255);\n"
"border-radius:5px;\n"
"color:#fff;\n"
"padding:4px;\n"
"cursor:pointer;\n"
"min-height:25px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background:#3559cf;\n"
"border:none;\n"
"color:white;\n"
"}\n"
"\n"
"QFrame{\n"
"background-color: rgba(255, 255, 255,0.1);\n"
"}\n"
"QFrame:hover{\n"
"background-color: rgba(231, 231, 231,0.13);\n"
"}\n"
"\n"
"\n"
"QLineEdit{\n"
"color:white;\n"
"background:transparent;\n"
"border:none;\n"
"border-bottom:0.04em solid #8f8f8f;\n"
"}\n"
"QLineEdit:hover{\n"
"background:rgba(0,0,0,0.06);\n"
"border-radius:6px;\n"
"border-bottom:none;\n"
"}\n"
"\n"
"QYedek{\n"
"border-bottom:0.04em solid #b0b0b0\n"
"}\n"
"")
        self.topFrame.setObjectName("topFrame")
        self.top_layout = QtWidgets.QHBoxLayout(self.topFrame)
        self.top_layout.setContentsMargins(0, 0, 0, 0)
        self.top_layout.setSpacing(0)
        self.top_layout.setObjectName("top_layout")
        self.connectFrame = QtWidgets.QFrame(self.topFrame)
        self.connectFrame.setMinimumSize(QtCore.QSize(261, 261))
        self.connectFrame.setMaximumSize(QtCore.QSize(261, 16777215))
        self.connectFrame.setStyleSheet("QFrame:hover{\n"
"background-color: rgba(231, 231, 231,0.08);\n"
"}")
        self.connectFrame.setObjectName("connectFrame")
        self.label_2 = QtWidgets.QLabel(self.connectFrame)
        self.label_2.setGeometry(QtCore.QRect(10, -10, 241, 190))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("margin:0px;\n"
"background:transparent;\n"
"padding:0px;\n"
"margin-left:1px")
        self.label_2.setObjectName("label_2")
        self.lineEdit = QtWidgets.QLineEdit(self.connectFrame)
        self.lineEdit.setGeometry(QtCore.QRect(123, 154, 121, 50))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        self.lineEdit.setMinimumSize(QtCore.QSize(50, 50))
        self.lineEdit.setMaximumSize(QtCore.QSize(180, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit.setFont(font)
        self.lineEdit.setAutoFillBackground(False)
        self.lineEdit.setStyleSheet("")
        self.lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit.setObjectName("lineEdit")
        self.label_3 = QtWidgets.QLabel(self.connectFrame)
        self.label_3.setGeometry(QtCore.QRect(11, 157, 128, 50))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMinimumSize(QtCore.QSize(0, 0))
        self.label_3.setMaximumSize(QtCore.QSize(128, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("background:none;\n"
"color:rgb(206, 206, 206);")
        self.label_3.setObjectName("label_3")
        self.pushButton_2 = QtWidgets.QPushButton(self.connectFrame)
        self.pushButton_2.setGeometry(QtCore.QRect(12, 197, 121, 53))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"background-color:rgb(17, 199, 14);\n"
"border-radius:5px;\n"
"color:#fff;\n"
"padding:4px;\n"
"cursor:pointer;\n"
"min-height:25px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background:#0d9f0a;\n"
"border:none;\n"
"color:white;\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton = QtWidgets.QPushButton(self.connectFrame)
        self.pushButton.setGeometry(QtCore.QRect(127, 198, 121, 53))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton.setFont(font)
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setStyleSheet("QPushButton{\n"
"background:rgb(255, 66, 69);\n"
"color:#fff;\n"
"}\n"
"QPushButton:hover{\n"
"border:none;\n"
"background:#f32d31;\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.top_layout.addWidget(self.connectFrame)
        self.dataFrame = QtWidgets.QFrame(self.topFrame)
        self.dataFrame.setMinimumSize(QtCore.QSize(828, 261))
        self.dataFrame.setMaximumSize(QtCore.QSize(828, 16777215))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        self.dataFrame.setFont(font)
        self.dataFrame.setStyleSheet("QLabel{\n"
"background:none;\n"
"color:rgb(206, 206, 206);\n"
"font-size:17px;\n"
"margin:1px;\n"
"padding:7px;\n"
"padding-left:27px;\n"
"}\n"
"\n"
"QLineEdit{\n"
"font-size:20px;\n"
"font-family:Yu Gothic UI;\n"
"border-bottom:none;\n"
"margin:0px;\n"
"padding:0px;\n"
"}\n"
"QLineEdit:hover{\n"
"background:transparent;;\n"
"border-radius:0px;\n"
"border:none;\n"
"}\n"
"QFrame{\n"
"padding:7px;\n"
"padding-left:9px;\n"
"padding-right:9px;\n"
"}\n"
"QFrame:hover{\n"
"background-color: rgba(231, 231, 231,0.08);\n"
"}")
        self.dataFrame.setObjectName("dataFrame")
        self.label_4 = QtWidgets.QLabel(self.dataFrame)
        self.label_4.setGeometry(QtCore.QRect(26, 17, 139, 37))
        self.label_4.setObjectName("label_4")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.dataFrame)
        self.lineEdit_3.setGeometry(QtCore.QRect(165, 54, 154, 30))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(-1)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setStyleSheet("")
        self.lineEdit_3.setReadOnly(True)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_5 = QtWidgets.QLabel(self.dataFrame)
        self.label_5.setGeometry(QtCore.QRect(45, 52, 120, 37))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.dataFrame)
        self.label_6.setGeometry(QtCore.QRect(95, 87, 70, 37))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.dataFrame)
        self.label_7.setGeometry(QtCore.QRect(39, 122, 126, 37))
        self.label_7.setObjectName("label_7")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.dataFrame)
        self.lineEdit_2.setEnabled(True)
        self.lineEdit_2.setGeometry(QtCore.QRect(165, 19, 154, 30))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(-1)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setInputMethodHints(QtCore.Qt.ImhNone)
        self.lineEdit_2.setReadOnly(True)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.dataFrame)
        self.lineEdit_4.setGeometry(QtCore.QRect(165, 89, 154, 30))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(-1)
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setReadOnly(True)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_9 = QtWidgets.QLabel(self.dataFrame)
        self.label_9.setGeometry(QtCore.QRect(371, 19, 88, 37))
        self.label_9.setObjectName("label_9")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.dataFrame)
        self.lineEdit_7.setGeometry(QtCore.QRect(456, 21, 84, 30))
        self.lineEdit_7.setReadOnly(True)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.dataFrame)
        self.lineEdit_5.setGeometry(QtCore.QRect(165, 124, 154, 30))
        self.lineEdit_5.setReadOnly(True)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.label_14 = QtWidgets.QLabel(self.dataFrame)
        self.label_14.setGeometry(QtCore.QRect(357, 56, 102, 37))
        self.label_14.setObjectName("label_14")
        self.lineEdit_12 = QtWidgets.QLineEdit(self.dataFrame)
        self.lineEdit_12.setGeometry(QtCore.QRect(456, 58, 84, 30))
        self.lineEdit_12.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit_12.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lineEdit_12.setStyleSheet("")
        self.lineEdit_12.setReadOnly(True)
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.lineEdit_16 = QtWidgets.QLineEdit(self.dataFrame)
        self.lineEdit_16.setGeometry(QtCore.QRect(456, 95, 84, 30))
        self.lineEdit_16.setReadOnly(True)
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.dataFrame)
        self.lineEdit_6.setGeometry(QtCore.QRect(165, 160, 154, 28))
        self.lineEdit_6.setMinimumSize(QtCore.QSize(154, 28))
        self.lineEdit_6.setMaximumSize(QtCore.QSize(154, 16777215))
        self.lineEdit_6.setStyleSheet("\n"
"color:rgb(255, 255, 255);\n"
"border-radius:10px;\n"
"margin:0px;")
        self.lineEdit_6.setReadOnly(True)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.label_8 = QtWidgets.QLabel(self.dataFrame)
        self.label_8.setGeometry(QtCore.QRect(19, 157, 146, 37))
        self.label_8.setObjectName("label_8")
        self.label_19 = QtWidgets.QLabel(self.dataFrame)
        self.label_19.setGeometry(QtCore.QRect(377, 93, 82, 37))
        self.label_19.setObjectName("label_19")
        self.lineEdit_17 = QtWidgets.QLineEdit(self.dataFrame)
        self.lineEdit_17.setGeometry(QtCore.QRect(141, 207, 50, 30))
        self.lineEdit_17.setMaximumSize(QtCore.QSize(50, 16777215))
        self.lineEdit_17.setReadOnly(True)
        self.lineEdit_17.setObjectName("lineEdit_17")
        self.label_13 = QtWidgets.QLabel(self.dataFrame)
        self.label_13.setGeometry(QtCore.QRect(373, 130, 86, 37))
        self.label_13.setObjectName("label_13")
        self.lineEdit_11 = QtWidgets.QLineEdit(self.dataFrame)
        self.lineEdit_11.setGeometry(QtCore.QRect(456, 132, 84, 30))
        self.lineEdit_11.setReadOnly(True)
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.label_21 = QtWidgets.QLabel(self.dataFrame)
        self.label_21.setGeometry(QtCore.QRect(342, 167, 117, 37))
        self.label_21.setObjectName("label_21")
        self.lineEdit_18 = QtWidgets.QLineEdit(self.dataFrame)
        self.lineEdit_18.setGeometry(QtCore.QRect(456, 169, 84, 30))
        self.lineEdit_18.setReadOnly(True)
        self.lineEdit_18.setObjectName("lineEdit_18")
        self.label_22 = QtWidgets.QLabel(self.dataFrame)
        self.label_22.setGeometry(QtCore.QRect(331, 204, 128, 37))
        self.label_22.setObjectName("label_22")
        self.lineEdit_19 = QtWidgets.QLineEdit(self.dataFrame)
        self.lineEdit_19.setGeometry(QtCore.QRect(456, 206, 84, 30))
        self.lineEdit_19.setReadOnly(True)
        self.lineEdit_19.setObjectName("lineEdit_19")
        self.label_20 = QtWidgets.QLabel(self.dataFrame)
        self.label_20.setGeometry(QtCore.QRect(14, 205, 131, 37))
        self.label_20.setObjectName("label_20")
        self.pushButton_7 = QtWidgets.QPushButton(self.dataFrame)
        self.pushButton_7.setGeometry(QtCore.QRect(248, 211, 46, 29))
        self.pushButton_7.setMinimumSize(QtCore.QSize(0, 25))
        self.pushButton_7.setMaximumSize(QtCore.QSize(80, 29))
        font = QtGui.QFont()
        font.setFamily("MS Serif")
        font.setPointSize(19)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_7.setStyleSheet("QPushButton{\n"
"color:rgb(255, 255, 255);\n"
"background-color:#f32d31;\n"
"border-radius:10px;;\n"
"padding:0px;\n"
"margin:0px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color:#d4171d;\n"
"}\n"
"")
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.dataFrame)
        self.pushButton_8.setGeometry(QtCore.QRect(195, 211, 46, 27))
        self.pushButton_8.setMinimumSize(QtCore.QSize(0, 27))
        self.pushButton_8.setMaximumSize(QtCore.QSize(80, 27))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_8.setStyleSheet("QPushButton{\n"
"color:rgb(255, 255, 255);\n"
"background-color:#14eb10;\n"
"border-radius:10px;;\n"
"padding:0px;\n"
"margin:0px;\n"
"padding-bottom:2px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color:#15bf0c;\n"
"}")
        self.pushButton_8.setObjectName("pushButton_8")
        self.line_2 = QtWidgets.QFrame(self.dataFrame)
        self.line_2.setGeometry(QtCore.QRect(307, 25, 20, 211))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.dataFrame)
        self.line_3.setGeometry(QtCore.QRect(40, 189, 221, 21))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(self.dataFrame)
        self.line_4.setGeometry(QtCore.QRect(555, 25, 20, 211))
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.lineEdit_20 = QtWidgets.QLineEdit(self.dataFrame)
        self.lineEdit_20.setGeometry(QtCore.QRect(687, 206, 84, 30))
        self.lineEdit_20.setReadOnly(True)
        self.lineEdit_20.setObjectName("lineEdit_20")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.dataFrame)
        self.lineEdit_8.setGeometry(QtCore.QRect(687, 21, 101, 30))
        self.lineEdit_8.setReadOnly(True)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.lineEdit_21 = QtWidgets.QLineEdit(self.dataFrame)
        self.lineEdit_21.setGeometry(QtCore.QRect(687, 169, 84, 30))
        self.lineEdit_21.setReadOnly(True)
        self.lineEdit_21.setObjectName("lineEdit_21")
        self.label_10 = QtWidgets.QLabel(self.dataFrame)
        self.label_10.setGeometry(QtCore.QRect(599, 19, 91, 37))
        self.label_10.setObjectName("label_10")
        self.label_25 = QtWidgets.QLabel(self.dataFrame)
        self.label_25.setGeometry(QtCore.QRect(629, 204, 61, 37))
        self.label_25.setObjectName("label_25")
        self.lineEdit_22 = QtWidgets.QLineEdit(self.dataFrame)
        self.lineEdit_22.setGeometry(QtCore.QRect(687, 95, 84, 30))
        self.lineEdit_22.setReadOnly(True)
        self.lineEdit_22.setObjectName("lineEdit_22")
        self.label_26 = QtWidgets.QLabel(self.dataFrame)
        self.label_26.setGeometry(QtCore.QRect(631, 167, 61, 37))
        self.label_26.setObjectName("label_26")
        self.lineEdit_13 = QtWidgets.QLineEdit(self.dataFrame)
        self.lineEdit_13.setGeometry(QtCore.QRect(687, 132, 84, 30))
        self.lineEdit_13.setReadOnly(True)
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.lineEdit_15 = QtWidgets.QLineEdit(self.dataFrame)
        self.lineEdit_15.setGeometry(QtCore.QRect(687, 58, 101, 30))
        self.lineEdit_15.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit_15.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lineEdit_15.setStyleSheet("")
        self.lineEdit_15.setReadOnly(True)
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.label_15 = QtWidgets.QLabel(self.dataFrame)
        self.label_15.setGeometry(QtCore.QRect(588, 56, 102, 37))
        self.label_15.setObjectName("label_15")
        self.label_28 = QtWidgets.QLabel(self.dataFrame)
        self.label_28.setGeometry(QtCore.QRect(601, 93, 91, 37))
        self.label_28.setObjectName("label_28")
        self.label_16 = QtWidgets.QLabel(self.dataFrame)
        self.label_16.setGeometry(QtCore.QRect(623, 130, 71, 37))
        self.label_16.setObjectName("label_16")
        self.top_layout.addWidget(self.dataFrame)
        self.operationsFrame = QtWidgets.QFrame(self.topFrame)
        self.operationsFrame.setMinimumSize(QtCore.QSize(0, 0))
        self.operationsFrame.setMaximumSize(QtCore.QSize(10000, 16777215))
        self.operationsFrame.setStyleSheet("QLabel{\n"
"background:none;\n"
"color:rgb(206, 206, 206);\n"
"font-size:17px;\n"
"margin:0px;\n"
"padding:0px;\n"
"}\n"
"QPushButton{\n"
"padding:0px;\n"
"padding-left:0px;\n"
"margin:0px;\n"
"margin-right:4px;\n"
"}\n"
"\n"
"QLineEdit{\n"
"font-size:20px;\n"
"font-family:Yu Gothic UI;\n"
"border-bottom:none;\n"
"margin:0px;\n"
"padding:0px;\n"
"}\n"
"QLineEdit:hover{\n"
"background:transparent;;\n"
"border-radius:0px;\n"
"border:none;\n"
"}\n"
"QFrame{\n"
"padding:6px;\n"
"padding-bottom:2px;\n"
"}\n"
"QFrame:hover{\n"
"background-color: rgba(231, 231, 231,0.08);\n"
"}\n"
"\n"
"")
        self.operationsFrame.setObjectName("operationsFrame")
        self.gridLayout = QtWidgets.QGridLayout(self.operationsFrame)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_18 = QtWidgets.QLabel(self.operationsFrame)
        self.label_18.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.label_18.setFont(font)
        self.label_18.setStyleSheet("QLabel{\n"
"font-size:18px;\n"
"padding:0px;\n"
"padding-right:1px;\n"
"padding-left:6px;\n"
"}\n"
"\n"
"QLabel:hover{\n"
"background-color:none;\n"
"}")
        self.label_18.setObjectName("label_18")
        self.gridLayout.addWidget(self.label_18, 1, 0, 1, 1, QtCore.Qt.AlignRight)
        self.lineEdit_14 = QtWidgets.QLineEdit(self.operationsFrame)
        self.lineEdit_14.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit_14.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lineEdit_14.setStyleSheet("QLineEdit{\n"
"font-size:18px;\n"
"font-family:Yu Gothic UI;\n"
"border-bottom:none;\n"
"margin:0px;\n"
"padding-left:2px;\n"
"padding-right:2px;\n"
"background-color: rgba(220, 220, 220,0.1);\n"
"border-radius:3px;\n"
"}\n"
"QLineEdit:hover{\n"
"background:transparent;;\n"
"border-radius:0px;\n"
"border:none;\n"
"background-color: rgba(220, 220, 220,0.16);\n"
"}")
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.gridLayout.addWidget(self.lineEdit_14, 1, 1, 1, 2)
        self.pushButton_6 = QtWidgets.QPushButton(self.operationsFrame)
        self.pushButton_6.setMinimumSize(QtCore.QSize(30, 25))
        self.pushButton_6.setMaximumSize(QtCore.QSize(30, 29))
        self.pushButton_6.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_6.setStyleSheet("QPushButton{\n"
"border-radius:3px;\n"
"font-size:18px;\n"
"padding:0px;\n"
"border-radius:1px;\n"
"background-color: rgba(220, 220, 220,0.1);\n"
"margin:0px;\n"
"margin-left:0px\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"\n"
"background-color: rgba(220, 220, 220,0.16);\n"
"}")
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout.addWidget(self.pushButton_6, 1, 3, 1, 1)
        self.pushButton_5 = QtWidgets.QPushButton(self.operationsFrame)
        self.pushButton_5.setMinimumSize(QtCore.QSize(114, 25))
        self.pushButton_5.setMaximumSize(QtCore.QSize(1000, 35))
        self.pushButton_5.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_5.setStyleSheet("QPushButton{\n"
"border-radius:3px;\n"
"font-size:18px;\n"
"border-radius:4px;\n"
"padding:0px;\n"
"\n"
"}\n"
"\n"
"\n"
"QPushButton:hover{\n"
"background-color: #4363d8;\n"
"}")
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout.addWidget(self.pushButton_5, 1, 4, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 8, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 2, 0, 1, 5)
        self.pushButton_3 = QtWidgets.QPushButton(self.operationsFrame)
        self.pushButton_3.setMinimumSize(QtCore.QSize(0, 25))
        self.pushButton_3.setMaximumSize(QtCore.QSize(250, 35))
        self.pushButton_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_3.setStyleSheet("QPushButton{\n"
"font-size:14px;\n"
"border-radius:3px;\n"
"background-color:#737373;\n"
"padding:0px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: #646464;\n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout.addWidget(self.pushButton_3, 3, 3, 1, 2)
        spacerItem1 = QtWidgets.QSpacerItem(40, 8, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 4, 0, 1, 5)
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.operationsFrame)
        self.plainTextEdit.setMinimumSize(QtCore.QSize(314, 120))
        self.plainTextEdit.setStyleSheet("background-color:rgba(0, 0, 0,0.3);\n"
"color: rgb(232, 232, 232);\n"
"font-size:15px;\n"
"border:none;\n"
"border-radius:5px;\n"
"margin-top:0px;")
        self.plainTextEdit.setLineWidth(1)
        self.plainTextEdit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.plainTextEdit.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.plainTextEdit.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.plainTextEdit.setLineWrapMode(QtWidgets.QPlainTextEdit.WidgetWidth)
        self.plainTextEdit.setReadOnly(True)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.gridLayout.addWidget(self.plainTextEdit, 5, 0, 3, 3)
        self.pushButton_9 = QtWidgets.QPushButton(self.operationsFrame)
        self.pushButton_9.setMinimumSize(QtCore.QSize(195, 55))
        self.pushButton_9.setMaximumSize(QtCore.QSize(10000, 350))
        self.pushButton_9.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_9.setStyleSheet("QPushButton{\n"
"color:rgb(255, 255, 255);\n"
"background-color:rgba(243, 45, 49,0.62);\n"
"border-radius:3px;\n"
"font-size:21px;\n"
"border-radius:10px;\n"
"padding:10px;\n"
"margin-bottom:10px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color:#c81215;\n"
"}")
        self.pushButton_9.setObjectName("pushButton_9")
        self.gridLayout.addWidget(self.pushButton_9, 5, 3, 3, 2)
        self.label_23 = QtWidgets.QLabel(self.operationsFrame)
        self.label_23.setMinimumSize(QtCore.QSize(0, 0))
        self.label_23.setMaximumSize(QtCore.QSize(16777215, 35))
        self.label_23.setStyleSheet("color:rgb(255, 255, 255);\n"
"background-color:rgba(243, 45, 49,0.4);\n"
"border-radius:3px;\n"
"font-size:14px;\n"
"border-radius:3px;\n"
"padding:0px;\n"
"padding-bottom:2px;\n"
"margin:0px;\n"
"padding-left:6px;\n"
"\n"
"")
        self.label_23.setAlignment(QtCore.Qt.AlignCenter)
        self.label_23.setObjectName("label_23")
        self.gridLayout.addWidget(self.label_23, 3, 1, 1, 2)
        self.label_24 = QtWidgets.QLabel(self.operationsFrame)
        self.label_24.setMaximumSize(QtCore.QSize(155, 16777215))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.label_24.setFont(font)
        self.label_24.setStyleSheet("QLabel{\n"
"font-size:18px;\n"
"padding:0px;\n"
"padding-right:1px;\n"
"padding-left:6px;\n"
"\n"
"}\n"
"\n"
"QLabel:hover{\n"
"background-color:none;\n"
"}")
        self.label_24.setObjectName("label_24")
        self.gridLayout.addWidget(self.label_24, 3, 0, 1, 1, QtCore.Qt.AlignRight)
        self.top_layout.addWidget(self.operationsFrame)
        self.gridLayout_3.addWidget(self.topFrame, 0, 0, 1, 2)
        self.graphicsFrame = QtWidgets.QFrame(self.frame)
        self.graphicsFrame.setMinimumSize(QtCore.QSize(200, 500))
        self.graphicsFrame.setMaximumSize(QtCore.QSize(580, 16777215))
        self.graphicsFrame.setStyleSheet("QFrame:hover{\n"
"background-color: rgba(231, 231, 231,0.13);\n"
"}\n"
"")
        self.graphicsFrame.setObjectName("graphicsFrame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.graphicsFrame)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.graphicsView_5 = QtWidgets.QGraphicsView(self.graphicsFrame)
        self.graphicsView_5.setAccessibleDescription("")
        self.graphicsView_5.setObjectName("graphicsView_5")
        self.gridLayout_2.addWidget(self.graphicsView_5, 0, 0, 1, 1)
        self.graphicsView_12 = QtWidgets.QGraphicsView(self.graphicsFrame)
        self.graphicsView_12.setObjectName("graphicsView_12")
        self.gridLayout_2.addWidget(self.graphicsView_12, 1, 1, 1, 2)
        self.graphicsView_6 = QtWidgets.QGraphicsView(self.graphicsFrame)
        self.graphicsView_6.setObjectName("graphicsView_6")
        self.gridLayout_2.addWidget(self.graphicsView_6, 0, 1, 1, 1)
        self.graphicsView_4 = QtWidgets.QGraphicsView(self.graphicsFrame)
        self.graphicsView_4.setObjectName("graphicsView_4")
        self.gridLayout_2.addWidget(self.graphicsView_4, 1, 0, 1, 1)
        self.graphicsView_8 = QtWidgets.QGraphicsView(self.graphicsFrame)
        self.graphicsView_8.setObjectName("graphicsView_8")
        self.gridLayout_2.addWidget(self.graphicsView_8, 2, 0, 1, 1)
        self.graphicsView_7 = QtWidgets.QGraphicsView(self.graphicsFrame)
        self.graphicsView_7.setObjectName("graphicsView_7")
        self.gridLayout_2.addWidget(self.graphicsView_7, 2, 1, 1, 1)
        self.gridLayout_3.addWidget(self.graphicsFrame, 1, 1, 2, 1)
        self.viewsFrame = QtWidgets.QFrame(self.frame)
        self.viewsFrame.setStyleSheet("QLabel{\n"
"background:none;\n"
"color:rgb(206, 206, 206);\n"
"font-size:17px;\n"
"margin:1px;\n"
"padding:7px;\n"
"padding-left:27px;\n"
"}\n"
"\n"
"QLineEdit{\n"
"font-size:20px;\n"
"font-family:Yu Gothic UI;\n"
"border-bottom:none;\n"
"margin:0px;\n"
"padding:0px;\n"
"}\n"
"QLineEdit:hover{\n"
"background:transparent;;\n"
"border-radius:0px;\n"
"border:none;\n"
"}\n"
"QFrame{\n"
"padding:0px;\n"
"padding-left:0px;\n"
"padding-right:0px;\n"
"margin:9px;\n"
"margin-left:12px;\n"
"margin-right:12px;\n"
"}\n"
"QFrame:hover{\n"
"background-color: rgba(231, 231, 231,0.13);\n"
"}\n"
"")
        self.viewsFrame.setObjectName("viewsFrame")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.viewsFrame)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.map = QtWidgets.QFrame(self.viewsFrame)
        self.map.setMinimumSize(QtCore.QSize(200, 200))
        self.map.setMaximumSize(QtCore.QSize(800, 500))
        self.map.setStyleSheet("QFrame{\n"
"margin:9px;\n"
"margin-left:12px;\n"
"margin-right:0px;\n"
"margin-bottom:6px;\n"
"}")
        self.map.setObjectName("map")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.map)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.mapLabel = QtWidgets.QLabel(self.map)
        self.mapLabel.setMinimumSize(QtCore.QSize(0, 0))
        self.mapLabel.setStyleSheet("border-radius:5px;\n"
"border:2px solid qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(63, 91, 255, 255), stop:0.55 rgba(235, 148, 61, 255), stop:0.98 rgba(0, 0, 0, 255), stop:1 rgba(0, 0, 0, 0))")
        self.mapLabel.setObjectName("mapLabel")
        self.gridLayout_10.addWidget(self.mapLabel, 0, 0, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.gridLayout_4.addWidget(self.map, 0, 0, 1, 1)
        self.threeD = QtWidgets.QFrame(self.viewsFrame)
        self.threeD.setMinimumSize(QtCore.QSize(200, 200))
        self.threeD.setMaximumSize(QtCore.QSize(800, 500))
        self.threeD.setStyleSheet("QFrame{\n"
"margin:9px;\n"
"margin-left:12px;\n"
"margin-right:0px;\n"
"margin-top:0px\n"
"}")
        self.threeD.setObjectName("threeD")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.threeD)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.threeDLabel = QtWidgets.QLabel(self.threeD)
        self.threeDLabel.setMinimumSize(QtCore.QSize(0, 0))
        self.threeDLabel.setStyleSheet("border-radius:5px;\n"
"border:2px solid qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(63, 91, 255, 255), stop:0.55 rgba(235, 148, 61, 255), stop:0.98 rgba(0, 0, 0, 255), stop:1 rgba(0, 0, 0, 0))")
        self.threeDLabel.setObjectName("threeDLabel")
        self.gridLayout_12.addWidget(self.threeDLabel, 0, 0, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.gridLayout_4.addWidget(self.threeD, 1, 0, 1, 1)
        self.cameraFrame = QtWidgets.QFrame(self.viewsFrame)
        self.cameraFrame.setMinimumSize(QtCore.QSize(750, 200))
        self.cameraFrame.setMaximumSize(QtCore.QSize(800, 16777215))
        self.cameraFrame.setStyleSheet("QFrame{\n"
"margin-left:6px;\n"
"padding:3px;\n"
"}")
        self.cameraFrame.setObjectName("cameraFrame")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.cameraFrame)
        self.gridLayout_11.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_11.setSpacing(0)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.startCameraButton = QtWidgets.QPushButton(self.cameraFrame)
        self.startCameraButton.setStyleSheet("background:transparent;")
        self.startCameraButton.setText("")
        self.startCameraButton.setObjectName("startCameraButton")
        self.gridLayout_11.addWidget(self.startCameraButton, 1, 0, 1, 1)
        self.cameraViewerLabel = QtWidgets.QLabel(self.cameraFrame)
        self.cameraViewerLabel.setMinimumSize(QtCore.QSize(0, 0))
        self.cameraViewerLabel.setStyleSheet("border-radius:5px;\n"
"border:2px solid qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(63, 91, 255, 255), stop:0.55 rgba(235, 148, 61, 255), stop:0.98 rgba(0, 0, 0, 255), stop:1 rgba(0, 0, 0, 0))")
        self.cameraViewerLabel.setObjectName("cameraViewerLabel")
        self.gridLayout_11.addWidget(self.cameraViewerLabel, 0, 0, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.gridLayout_4.addWidget(self.cameraFrame, 0, 1, 2, 1)
        self.gridLayout_3.addWidget(self.viewsFrame, 1, 0, 2, 1)
        self.verticalLayout_2.addWidget(self.frame)
        MainGUI.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainGUI)
        self.statusbar.setMinimumSize(QtCore.QSize(0, 35))
        self.statusbar.setSizeGripEnabled(True)
        self.statusbar.setObjectName("statusbar")
        MainGUI.setStatusBar(self.statusbar)

        self.retranslateUi(MainGUI)
        QtCore.QMetaObject.connectSlotsByName(MainGUI)

    def retranslateUi(self, MainGUI):
        _translate = QtCore.QCoreApplication.translate
        MainGUI.setWindowTitle(_translate("MainGUI", "TM MARM-99 YER ISTASYONU"))
        self.label.setText(_translate("MainGUI", "<html><head/><body><p><img src=\":/tm_marm99/tm-marm-99-logo-bw.png\" width=\"20\" height=\"20\"/></p></body></html>"))
        self.title_label.setText(_translate("MainGUI", "TM MARM-99 YER ISTASYONU"))
        self.button_minimize.setText(_translate("MainGUI", "_"))
        self.button_max_min.setText(_translate("MainGUI", "🗖"))
        self.button_close.setText(_translate("MainGUI", "✕"))
        self.label_2.setText(_translate("MainGUI", "<html><head/><body><p><img src=\":/tm_marm99/ground-station-logo.png\" width=\"235\"  /></p></body></html>"))
        self.lineEdit.setText(_translate("MainGUI", "2391"))
        self.label_3.setText(_translate("MainGUI", "ENTER PORT:"))
        self.pushButton_2.setText(_translate("MainGUI", "Connect"))
        self.pushButton.setText(_translate("MainGUI", "Disconnect"))
        self.label_4.setText(_translate("MainGUI", "Team Number:"))
        self.lineEdit_3.setText(_translate("MainGUI", "1440"))
        self.label_5.setText(_translate("MainGUI", "Package No:"))
        self.label_6.setText(_translate("MainGUI", "Date:"))
        self.label_7.setText(_translate("MainGUI", "Hour(h:m:s):"))
        self.lineEdit_2.setText(_translate("MainGUI", "54103"))
        self.lineEdit_4.setText(_translate("MainGUI", "20.08.2021"))
        self.label_9.setText(_translate("MainGUI", "Sıcaklık:"))
        self.lineEdit_7.setText(_translate("MainGUI", "34.93"))
        self.lineEdit_5.setText(_translate("MainGUI", "09:10:11"))
        self.label_14.setText(_translate("MainGUI", "Yükseklik:"))
        self.lineEdit_12.setText(_translate("MainGUI", "-11.75"))
        self.lineEdit_16.setText(_translate("MainGUI", "1014.66"))
        self.lineEdit_6.setText(_translate("MainGUI", "Descending.."))
        self.label_8.setText(_translate("MainGUI", "Satellite Status:"))
        self.label_19.setText(_translate("MainGUI", "Basınç:"))
        self.lineEdit_17.setText(_translate("MainGUI", "8.24"))
        self.label_13.setText(_translate("MainGUI", "Gerilim:"))
        self.lineEdit_11.setText(_translate("MainGUI", "3.62"))
        self.label_21.setText(_translate("MainGUI", "Kanat Açısı:"))
        self.lineEdit_18.setText(_translate("MainGUI", "3.72"))
        self.label_22.setText(_translate("MainGUI", "Dönüş Sayısı:"))
        self.lineEdit_19.setText(_translate("MainGUI", "12"))
        self.label_20.setText(_translate("MainGUI", "Descent Rate:"))
        self.pushButton_7.setText(_translate("MainGUI", "-"))
        self.pushButton_8.setText(_translate("MainGUI", "+"))
        self.lineEdit_20.setText(_translate("MainGUI", "147.703"))
        self.lineEdit_8.setText(_translate("MainGUI", "40.651853"))
        self.lineEdit_21.setText(_translate("MainGUI", "114.228"))
        self.label_10.setText(_translate("MainGUI", "Latitude:"))
        self.label_25.setText(_translate("MainGUI", "Yaw:"))
        self.lineEdit_22.setText(_translate("MainGUI", "13"))
        self.label_26.setText(_translate("MainGUI", "Roll:"))
        self.lineEdit_13.setText(_translate("MainGUI", "-30.375"))
        self.lineEdit_15.setText(_translate("MainGUI", "29.288874"))
        self.label_15.setText(_translate("MainGUI", "Longitude:"))
        self.label_28.setText(_translate("MainGUI", "Altitude:"))
        self.label_16.setText(_translate("MainGUI", "Pitch:"))
        self.label_18.setText(_translate("MainGUI", "Data Transfer:"))
        self.lineEdit_14.setText(_translate("MainGUI", "some_cool_data.xml"))
        self.pushButton_6.setText(_translate("MainGUI", ".."))
        self.pushButton_5.setText(_translate("MainGUI", "Sent"))
        self.pushButton_3.setText(_translate("MainGUI", "Upload CSV File"))
        self.plainTextEdit.setPlainText(_translate("MainGUI", "Telemetri: GPS verileri güncellenemedi.\n"
"Telemetri: Gerçek zamanlı video yüklenemedi.\n"
"Telemetri: Uydu pervanesine martı çarptı.\n"
"Telemetri: Uydu gözden kayboluyor.\n"
"Telemetri: Bir şeyler çok fena ters gitti.\n"
"Telemetri: Uydu Allah`a emanet.\n"
"Bağlantı: Port bağlantısı kesildi."))
        self.pushButton_9.setText(_translate("MainGUI", "Manual\n"
"LEAVE PAYLOAD\n"
"Command"))
        self.label_23.setText(_translate("MainGUI", "Not Transferring"))
        self.label_24.setText(_translate("MainGUI", "Video Transfer:"))
        self.mapLabel.setText(_translate("MainGUI", "Map"))
        self.threeDLabel.setText(_translate("MainGUI", "3D"))
        self.cameraViewerLabel.setText(_translate("MainGUI", "Camera"))
from images import tm_marm99_rc
