# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Lenovo\Desktop\KOU\TM MARM-99 2021\turksat-muy-ground-station-2021\templates\MainGUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainGUI(object):
    def setupUi(self, MainGUI):
        MainGUI.setObjectName("MainGUI")
        MainGUI.resize(929, 740)
        self.centralwidget = QtWidgets.QWidget(MainGUI)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.main_layout = QtWidgets.QGridLayout()
        self.main_layout.setObjectName("main_layout")
        self.top_layout = QtWidgets.QHBoxLayout()
        self.top_layout.setObjectName("top_layout")
        self.port = QtWidgets.QVBoxLayout()
        self.port.setObjectName("port")
        self.top_layout.addLayout(self.port)
        self.data = QtWidgets.QVBoxLayout()
        self.data.setObjectName("data")
        self.top_layout.addLayout(self.data)
        self.data_transfer = QtWidgets.QVBoxLayout()
        self.data_transfer.setObjectName("data_transfer")
        self.top_layout.addLayout(self.data_transfer)
        self.main_layout.addLayout(self.top_layout, 0, 0, 1, 1)
        self.mid_layout = QtWidgets.QHBoxLayout()
        self.mid_layout.setObjectName("mid_layout")
        self.main_layout.addLayout(self.mid_layout, 1, 0, 1, 1)
        self.bottom_layout = QtWidgets.QHBoxLayout()
        self.bottom_layout.setObjectName("bottom_layout")
        self.main_layout.addLayout(self.bottom_layout, 2, 0, 1, 1)
        self.verticalLayout_2.addLayout(self.main_layout)
        MainGUI.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainGUI)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 929, 26))
        self.menubar.setNativeMenuBar(False)
        self.menubar.setObjectName("menubar")
        MainGUI.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainGUI)
        self.statusbar.setSizeGripEnabled(True)
        self.statusbar.setObjectName("statusbar")
        MainGUI.setStatusBar(self.statusbar)

        self.retranslateUi(MainGUI)
        QtCore.QMetaObject.connectSlotsByName(MainGUI)

    def retranslateUi(self, MainGUI):
        _translate = QtCore.QCoreApplication.translate
        MainGUI.setWindowTitle(_translate("MainGUI", "TM MARM-99 YER ISTASYONU"))
